apiVersion: v1
kind: Service
metadata:
  name: django-bench
  labels:
    app: django-bench
spec:
  type: NodePort
  selector:
    app: django-bench
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      protocol: TCP
