apiVersion: v1
kind: Service
metadata:
  name: go-bench
  labels:
    app: go-bench
spec:
  type: NodePort
  selector:
    app: go-bench
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
