apiVersion: v1
kind: Service
metadata:
  name: rust-bench
  labels:
    app: rust-bench
spec:
  type: NodePort
  selector:
    app: rust-bench
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
      protocol: TCP
